# Frontend Dockerfile

ARG NODE_VERSION=24.14.0-alpine

FROM node:${NODE_VERSION} AS builder


WORKDIR /app

COPY package.json package-lock.json ./


RUN npm install


COPY . .


RUN npm run build

# Vaihe 2: Käytä kevyempää Node.js -kuvaa tuotantovaiheeseen

FROM node:${NODE_VERSION} AS runner


ENV NODE_ENV=production

WORKDIR /app


COPY --link --from=builder /app/dist ./dist


RUN npm install --production


USER node


EXPOSE 3000


CMD ["npx", "serve", "-s", "dist", "-l", "3000"]