# Backend Dockerfile

ARG NODE_VERSION=24.14.0-alpine

FROM node:${NODE_VERSION} AS base


WORKDIR /app


COPY package*.json ./


RUN --mount=type=cache,target=/root/.npm npm ci --only=production


COPY . .


RUN chown -R node:node /app


USER node

EXPOSE 3000

CMD ["node", "index.js"]